modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
[[mods]]
modId="tisstring"
version="${file.jarVersion}"

displayName="TIS-Stringify"

logoFile="tisstring.png"

credits="thanks to PwnagePineapple for letting me fork their project to use as a base"

authors="Walksanator"

description='''
Adds some modules for working with strings (mainly for use with the terminal module)
'''

[[dependencies.tisstring]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tisstring]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tisstring]]
    modId="tis3d"
    mandatory=true
    versionRange="1.6.8"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tisstring]]
    modId="computercraft"
    mandatory=false